# mainly using for translation from parsing to validation

snapshot_map = {
    "Země": "country",  
    "Číslo": "number",
    "Hráč": "player",
    "Prestiž K": "prestiz",
    "Vojáků K": "vojaku",
    "Tanků K": "tanku",
    "Stíhaček K": "stihacky",
    "Bunkrů K": "bunkry",
    "Mechů K": "mechy",
    "Agentů": "agenti",
    "Operací": "operaci",
    "Konv rak": "konvencni",
    "Bio rak": "biocid",
    "Emp rak": "emp",
    "Nukl rak": "nuke",
    "Zkuš arm K": "zkusenosti_armady",
    "Hodnost": "hodnost",
    "Zkuš věk K": "zkusenosti_za_vek",
    "Sesvačenost": "sesvacenost",
    "T hospod K": "hospodarske_technologie",
    "T RychSt K": "rychlost_stavby",
    "T Obchod K": "obchod",
    "T HustZa K": "hustota_zalidneni",
    "T Zemědě K": "zemedelstvi",
    "T Továrn K": "automatizace_tovaren",
    "T Energe K": "energetika",
    "T vojen K": "vojenske_technologie",
    "T SílaZb K": "sila_zbrani",
    "T DomTrh K": "cena_na_domacim_trhu",
    "T Rakety K": "vyvoj_raket",
    "T Protir K": "pritraketova_obrana",
    "T Rozvěd K": "sila_rozvedka",
    "T Výzkum K": "vyzkum_versmiru",
    "Země": "zeme",
    "Obyvatel M": "pocet_obyvatel",
    "Peněz M": "penize",
    "Jídla K": "jidlo",
    "Energie K": "energie",
    "Spokoj": "spokojenost",
    "Na trhu": "ulozeno_na_trhu",
    "+peněz K": "prirustek_penez",
    "+jídla": "vypestovano_jidla",
    "+energie": "vyrobeno_energie",
    "+vojáků": "vycviceno_vojaku",
    "+dílů jedn": "vyrobeno_dilu_jednotek",
    "+technologií": "vyprodukovano_technologii",
    "Rozloha K": "rozhloha",
    "Vesnice K": "vesnic",
    "Města K": "mest",  
    "Obchod z K": "obchodnich_zon",
    "Farmy K": "farem",
    "Laborato K": "laboratori",
    "Továrny K": "tovaren",
    "Kasárny K": "kasaren",
    "Elektrár K": "elektraren",
    "Záb stř K": "zabavnych_stredisek",
    "Voj zákl K": "vojenskych_zakladen",
    "Staveb fir": "stavebnich_firem",
    "Nezastav K": "nezastaveno",
    "Ruiny K": "ruiny",
    "B vesnice": "bonus_vesnice",
    "B farmy": "bonus_farmy",
    "B laborat": "bonus_laboratore",
    "B továrny": "bonus_tovarny",
    "B kasárny": "bonus_kasarny",
    "B elektrár": "bonus_elektrarny",
    "B voj zákl": "bonus_vojenske_zakladny",
    "B peníze": "bonus_penize",
    "B max hosp": "bonus_max_hospodarskych_technologii",
    "B max voj": "bonus_max_vojenskych_technologii",
    "B efekt hosp": "bonus_efekt_hospodarskych_technologii",
    "B útok": "bonus_utok",
    "B obrana": "bonus_obrana",
    "B koloniz": "bonus_kolonizace",
    "B žoldy": "bonus_zoldy",
    "Země": "zeme",
    "Logout": "logout",
    "Rozvoj zač": "zacatek_rozvoje",
    "Hosp pomoc": "posledni_hospodarska_pomoc",
    "Dostal HP": "prichozich_hosp",
    "Poslal HP": "odchozich_hosp",
    "Ali Fórum": "posledni_zprava_na_aliancnim_foru",
    "Do poklad": "podil_do_pokladny",
    "Z poklad M": "vybrano_z_pokladny",
    "Vesmír": "prozkoumano_vesmiru",
    "Utop spok K": "bodu_utopie",
    "Android": "procento_androidu_v_populaci",
    "UFO": "sance_na_UFO",
    "Emb Hlas": "embargo_hlasu",
    "Odehr kola": "odhrana_kola",
    "Volná kola": "volna_kola",
    "Nepř kola": "nepristupna_kola"    
}

static_keys = set(snapshot_map.keys())


# Země | Číslo | Hráč | Prestiž K | Vojáků K | Tanků K | Stíhaček K | Bunkrů K | Mechů K | Agentů | Operací | Konv rak |
# Bio rak | Emp rak | Nukl rak | Zkuš arm K | Hodnost | Zkuš věk K | Sesvačenost | T hospod K | T RychSt K | T Obchod K |
# T HustZa K | T Zemědě K | T Továrn K | T Energe K | T vojen K | T SílaZb K | T DomTrh K | T Rakety K | T Protir K | T Rozvěd K |
# T Výzkum K | Země | Obyvatel M | Peněz M | Jídla K | Energie K | Spokoj | Na trhu | +peněz K | +jídla | +energie | +vojáků |
# +dílů jedn | +technologií | Rozloha K | Vesnice K | Města K | Obchod z K | Farmy K | Laborato K | Továrny K | Kasárny K |
# Elektrár K | Záb stř K | Voj zákl K | Staveb fir | Nezastav K | Ruiny K | B vesnice | B farmy | B laborat | B továrny |
# B kasárny | B elektrár | B voj zákl | B peníze | B max hosp | B max voj | B efekt hosp | B útok | B obrana | B koloniz |
# B žoldy | Země | Logout | Rozvoj zač | Hosp pomoc | Dostal HP | Poslal HP | Hum pomoc | Ali Fórum | Do poklad | Z poklad M |
# Vesmír | Utop spok K | Android | UFO | Emb Hlas | Odehr kola | Volná kola | Nepř kola